<%
chef_server_ip = ENV['CHEF_SERVER_IP'] ? ENV['CHEF_SERVER_IP'] : '192.168.33.34'
chef_node1_ip = ENV['CHEF_NODE1_IP'] ? ENV['CHEF_NODE1_IP'] : '192.168.33.35'
chef_node2_ip = ENV['CHEF_NODE2_IP'] ? ENV['CHEF_NODE2_IP'] : '192.168.33.36'
chef_analytics_ip = ENV['CHEF_ANALYTICS_IP'] ? ENV['CHEF_ANALYTICS_IP'] : '192.168.33.37'
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    attributes:
      chef_server12:
        topology: 'standalone'
        api_fqdn: 'standalone.vagrantup.com'
        write_hosts: true
        backend:
          fqdn: 'standalone.vagrantup.com'
          ipaddress: "<%= chef_server_ip %>"
          analytics_fqdn: 'analytics.vagrantup.com'
          analytics_ipaddress: "<%= chef_analytics_ip %>"
        nodes:
          node1.vagrantup.com: "<%= chef_node1_ip %>"
          node2.vagrantup.com: "<%= chef_node2_ip %>"

  - name: ubuntu-14.04
    driver:
    attributes:
      chef_server12:
        topology: 'standalone'
        api_fqdn: 'standalone.vagrantup.com'
        write_hosts: true
        backend:
          fqdn: 'standalone.vagrantup.com'
          ipaddress: "<%= chef_server_ip %>"
          analytics_fqdn: 'analytics.vagrantup.com'
          analytics_ipaddress: "<%= chef_analytics_ip %>"
        nodes:
          node1.vagrantup.com: "<%= chef_node1_ip %>"
          node2.vagrantup.com: "<%= chef_node2_ip %>"

suites:
  - name: standalone
    driver:
      vm_hostname: standalone.vagrantup.com
      network:
      - ["private_network", {ip: "<%= chef_server_ip %>"}]
      customize:
        memory: 1536
    run_list:
      - recipe[chef-server12::standalone]
    attributes:

  - name: analytics
    driver:
      vm_hostname: analytics.vagrantup.com
      network:
      - ["private_network", {ip: "<%= chef_analytics_ip %>"}]
      customize:
        memory: 1536
    run_list:
      - recipe[chef-server12::analytics]
    attributes:

  - name: node1
    driver:
      vm_hostname: node1.vagrantup.com
      network:
      - ["private_network", {ip: "<%= chef_node1_ip %>"}]
      customize:
        memory: 512
    run_list:
      - recipe[chef-server12::node]
    attributes:
      chef_server12:
        node_fqdn: node1.vagrantup.com
        node_ipaddress: "<%= chef_node1_ip %>"

  - name: node2
    driver:
      vm_hostname: node2.vagrantup.com
      network:
      - ["private_network", {ip: "<%= chef_node2_ip %>"}]
      customize:
        memory: 512
    run_list:
      - recipe[chef-server12::node]
    attributes:
      chef_server12:
        node_fqdn: node2.vagrantup.com
        node_ipaddress: "<%= chef_node2_ip %>"
